{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a4cf64a1-77ab-47c3-8634-0815fd6dfac4",
   "metadata": {},
   "source": [
    "# Travail de jointure des tables\n",
    "\\\n",
    "Dans ce notebook, nous allons étudier les différentes jointures possibles entre les tables, afin d'en dégager une (ou des) tables jointes intéressantes pour une étude météorologique par exemple."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c1dcab73-25cf-4cce-9b58-11525f25bd45",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from matplotlib import pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2d4dbd14-823f-4995-8711-6da9434688cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "#importation des tables et informations utiles (cf. notebook d'introduction)\n",
    "df_cities = pd.read_csv('data/cities.csv')\n",
    "df_countries = pd.read_csv('data/countries.csv')\n",
    "df_weather = pd.read_csv('data/daily-weather-cities.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "145f3110-a064-44de-a1f4-c228d8251376",
   "metadata": {},
   "source": [
    "Les dataframes **cities** et **weather** peuvent a priori être jointes d'après **station_id**.\n",
    "\n",
    "Néanmoins, comme la table **weather** ne possède que 4 villes, on s'attend à une jointure avec beaucoup de nouvelles données vides :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1315d924-d1ea-4054-8ca0-8f9c3384f4ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0       41515\n",
       "1       38954\n",
       "2       41560\n",
       "3       38947\n",
       "4       38987\n",
       "        ...  \n",
       "1240    67475\n",
       "1241    68030\n",
       "1242    67633\n",
       "1243    67775\n",
       "1244    67975\n",
       "Name: station_id, Length: 1245, dtype: object"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_cities['station_id']"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1f5c49b4-1e51-41c7-8b0f-e7158ab9bfb4",
   "metadata": {},
   "source": [
    "On remarque que les *station_id* de cities sont de type objet, alors que celles de **weather** sont des entiers.\n",
    "Pour pouvoir faire la jointure entre les deux, on doit d'abord convertir les indices de **cities** en int64 comme ceux de **weather**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "66914e5e-539d-4055-944e-9eceab31638f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#NE MARCHE PAS\n",
    "# df_cities['station_id'].astype(int)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "beb95d35-5b4d-4765-9a2b-ca77bb7327de",
   "metadata": {},
   "source": [
    "Problème : toutes les lignes de *station_id* ne sont pas des entiers.\n",
    "\n",
    "On va donc les identifier et voir ce qu'on en fait."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b3516229-eab9-42c9-8f89-f8220a68844c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['D4704', 'D1666', 'D1051', 'D3137', 'D6217', 'D5541', 'D6217', 'D1964', 'D2629', 'D6170', 'KPHF0', 'EDTR0', 'D5731']\n"
     ]
    }
   ],
   "source": [
    "problems = [val for val in df_cities['station_id'] if not val.isdigit()]\n",
    "print(problems)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "054c991b-4370-4044-9c12-e40d59e2a73c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "78          Bregenz\n",
      "264           Vejle\n",
      "338         Dresden\n",
      "345           Mainz\n",
      "348     Saarbrücken\n",
      "351       Wiesbaden\n",
      "370    St. George's\n",
      "586        Diekirch\n",
      "694          Arnhem\n",
      "794    Zielona Góra\n",
      "895       Jamestown\n",
      "991         Liestal\n",
      "993    Schaffhausen\n",
      "Name: city_name, dtype: object\n"
     ]
    }
   ],
   "source": [
    "villes_problematiques = df_cities.loc[df_cities['station_id'].isin(problems), 'city_name']\n",
    "print(villes_problematiques)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "706b3ed0-718b-4fe2-945d-50c02b7c31c5",
   "metadata": {},
   "source": [
    "Aucune des villes concernées n'est dans **weather**, on va donc pouvoir les supprimer de **cities** pour pouvoir faire la jointure voulue."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "0973ebb7-62ba-443b-a0e8-7183e25b5f06",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"print(villes_problematiques.index.tolist())\\ndf_cities_clean = df_cities.drop(villes_problematiques.index.tolist())\\ndf_cities_clean['station_id'].astype(int)\\ndf_weather['station_id'].astype(int)\\n\\ndf_merge = pd.merge(df_cities_clean, df_weather, how='right', on='station_id')\""
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#NE MARCHE PAS NON PLUS\n",
    "'''print(villes_problematiques.index.tolist())\n",
    "df_cities_clean = df_cities.drop(villes_problematiques.index.tolist())\n",
    "df_cities_clean['station_id'].astype(int)\n",
    "df_weather['station_id'].astype(int)\n",
    "\n",
    "df_merge = pd.merge(df_cities_clean, df_weather, how='right', on='station_id')'''"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b07d5604-fc92-4a2a-a4a4-ddc6508674f9",
   "metadata": {},
   "source": [
    "La colonne station_id est inutile dans le cadre de notre étude et complique le problème in fine, autant la supprimer..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "dc8419f1-e7f8-4450-8cc5-6dfd96ac82b0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>city_name</th>\n",
       "      <th>country</th>\n",
       "      <th>state</th>\n",
       "      <th>iso2</th>\n",
       "      <th>iso3</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Asadabad</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>Kunar</td>\n",
       "      <td>AF</td>\n",
       "      <td>AFG</td>\n",
       "      <td>34.866000</td>\n",
       "      <td>71.150005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Fayzabad</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>Badakhshan</td>\n",
       "      <td>AF</td>\n",
       "      <td>AFG</td>\n",
       "      <td>37.129761</td>\n",
       "      <td>70.579247</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jalalabad</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>Nangarhar</td>\n",
       "      <td>AF</td>\n",
       "      <td>AFG</td>\n",
       "      <td>34.441527</td>\n",
       "      <td>70.436103</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Kunduz</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>Kunduz</td>\n",
       "      <td>AF</td>\n",
       "      <td>AFG</td>\n",
       "      <td>36.727951</td>\n",
       "      <td>68.872530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Qala i Naw</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>Badghis</td>\n",
       "      <td>AF</td>\n",
       "      <td>AFG</td>\n",
       "      <td>34.983000</td>\n",
       "      <td>63.133300</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1240</th>\n",
       "      <td>Kasama</td>\n",
       "      <td>Zambia</td>\n",
       "      <td>Northern</td>\n",
       "      <td>ZM</td>\n",
       "      <td>ZMB</td>\n",
       "      <td>-10.199598</td>\n",
       "      <td>31.179947</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1241</th>\n",
       "      <td>Livingstone</td>\n",
       "      <td>Zambia</td>\n",
       "      <td>Southern</td>\n",
       "      <td>ZM</td>\n",
       "      <td>ZMB</td>\n",
       "      <td>-17.860009</td>\n",
       "      <td>25.860013</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1242</th>\n",
       "      <td>Mongu</td>\n",
       "      <td>Zambia</td>\n",
       "      <td>Western</td>\n",
       "      <td>ZM</td>\n",
       "      <td>ZMB</td>\n",
       "      <td>-15.279598</td>\n",
       "      <td>23.120025</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1243</th>\n",
       "      <td>Harare</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>Harare</td>\n",
       "      <td>ZW</td>\n",
       "      <td>ZWE</td>\n",
       "      <td>-17.817790</td>\n",
       "      <td>31.044709</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1244</th>\n",
       "      <td>Masvingo</td>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>Masvingo</td>\n",
       "      <td>ZW</td>\n",
       "      <td>ZWE</td>\n",
       "      <td>-20.059617</td>\n",
       "      <td>30.820020</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1245 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        city_name      country       state iso2 iso3   latitude  longitude\n",
       "0        Asadabad  Afghanistan       Kunar   AF  AFG  34.866000  71.150005\n",
       "1        Fayzabad  Afghanistan  Badakhshan   AF  AFG  37.129761  70.579247\n",
       "2       Jalalabad  Afghanistan   Nangarhar   AF  AFG  34.441527  70.436103\n",
       "3          Kunduz  Afghanistan      Kunduz   AF  AFG  36.727951  68.872530\n",
       "4      Qala i Naw  Afghanistan     Badghis   AF  AFG  34.983000  63.133300\n",
       "...           ...          ...         ...  ...  ...        ...        ...\n",
       "1240       Kasama       Zambia    Northern   ZM  ZMB -10.199598  31.179947\n",
       "1241  Livingstone       Zambia    Southern   ZM  ZMB -17.860009  25.860013\n",
       "1242        Mongu       Zambia     Western   ZM  ZMB -15.279598  23.120025\n",
       "1243       Harare     Zimbabwe      Harare   ZW  ZWE -17.817790  31.044709\n",
       "1244     Masvingo     Zimbabwe    Masvingo   ZW  ZWE -20.059617  30.820020\n",
       "\n",
       "[1245 rows x 7 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_cities.drop('station_id', axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b7c55671-6100-4c3c-a4cb-5a764e5407e5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>city_name</th>\n",
       "      <th>date</th>\n",
       "      <th>season</th>\n",
       "      <th>avg_temp_c</th>\n",
       "      <th>min_temp_c</th>\n",
       "      <th>max_temp_c</th>\n",
       "      <th>precipitation_mm</th>\n",
       "      <th>snow_depth_mm</th>\n",
       "      <th>avg_wind_dir_deg</th>\n",
       "      <th>avg_wind_speed_kmh</th>\n",
       "      <th>peak_wind_gust_kmh</th>\n",
       "      <th>avg_sea_level_pres_hpa</th>\n",
       "      <th>sunshine_total_min</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>1855-02-01</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-8.5</td>\n",
       "      <td>-4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>1855-02-02</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-12.1</td>\n",
       "      <td>-3.8</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>1855-02-03</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-17.5</td>\n",
       "      <td>-8.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>1855-02-04</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-11.4</td>\n",
       "      <td>-6.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>1855-02-05</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-7.5</td>\n",
       "      <td>-1.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193114</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>2023-08-30</td>\n",
       "      <td>Summer</td>\n",
       "      <td>15.6</td>\n",
       "      <td>11.9</td>\n",
       "      <td>19.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>239.0</td>\n",
       "      <td>9.8</td>\n",
       "      <td>24.1</td>\n",
       "      <td>1010.8</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193115</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>2023-08-31</td>\n",
       "      <td>Summer</td>\n",
       "      <td>16.2</td>\n",
       "      <td>12.0</td>\n",
       "      <td>21.1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>203.0</td>\n",
       "      <td>10.4</td>\n",
       "      <td>25.9</td>\n",
       "      <td>1012.1</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193116</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>2023-09-01</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>16.7</td>\n",
       "      <td>12.2</td>\n",
       "      <td>21.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>190.0</td>\n",
       "      <td>11.0</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1015.5</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193117</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>2023-09-02</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>17.6</td>\n",
       "      <td>13.3</td>\n",
       "      <td>22.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>226.0</td>\n",
       "      <td>11.7</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1017.5</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193118</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>2023-09-03</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>18.5</td>\n",
       "      <td>13.5</td>\n",
       "      <td>23.9</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>190.0</td>\n",
       "      <td>11.5</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1017.6</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>193119 rows × 13 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       city_name        date  season  avg_temp_c  min_temp_c  max_temp_c  \\\n",
       "0         Vienna  1855-02-01  Winter         NaN        -8.5        -4.0   \n",
       "1         Vienna  1855-02-02  Winter         NaN       -12.1        -3.8   \n",
       "2         Vienna  1855-02-03  Winter         NaN       -17.5        -8.3   \n",
       "3         Vienna  1855-02-04  Winter         NaN       -11.4        -6.3   \n",
       "4         Vienna  1855-02-05  Winter         NaN        -7.5        -1.3   \n",
       "...          ...         ...     ...         ...         ...         ...   \n",
       "193114    Berlin  2023-08-30  Summer        15.6        11.9        19.7   \n",
       "193115    Berlin  2023-08-31  Summer        16.2        12.0        21.1   \n",
       "193116    Berlin  2023-09-01  Autumn        16.7        12.2        21.7   \n",
       "193117    Berlin  2023-09-02  Autumn        17.6        13.3        22.5   \n",
       "193118    Berlin  2023-09-03  Autumn        18.5        13.5        23.9   \n",
       "\n",
       "        precipitation_mm  snow_depth_mm  avg_wind_dir_deg  avg_wind_speed_kmh  \\\n",
       "0                    NaN            NaN               NaN                 NaN   \n",
       "1                    NaN            NaN               NaN                 NaN   \n",
       "2                    NaN            NaN               NaN                 NaN   \n",
       "3                    NaN            NaN               NaN                 NaN   \n",
       "4                    NaN            NaN               NaN                 NaN   \n",
       "...                  ...            ...               ...                 ...   \n",
       "193114               NaN            NaN             239.0                 9.8   \n",
       "193115               NaN            NaN             203.0                10.4   \n",
       "193116               NaN            NaN             190.0                11.0   \n",
       "193117               NaN            NaN             226.0                11.7   \n",
       "193118               NaN            NaN             190.0                11.5   \n",
       "\n",
       "        peak_wind_gust_kmh  avg_sea_level_pres_hpa  sunshine_total_min  \n",
       "0                      NaN                     NaN                 NaN  \n",
       "1                      NaN                     NaN                 NaN  \n",
       "2                      NaN                     NaN                 NaN  \n",
       "3                      NaN                     NaN                 NaN  \n",
       "4                      NaN                     NaN                 NaN  \n",
       "...                    ...                     ...                 ...  \n",
       "193114                24.1                  1010.8                 NaN  \n",
       "193115                25.9                  1012.1                 NaN  \n",
       "193116                27.8                  1015.5                 NaN  \n",
       "193117                27.8                  1017.5                 NaN  \n",
       "193118                27.8                  1017.6                 NaN  \n",
       "\n",
       "[193119 rows x 13 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_weather.drop('station_id', axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "df33b86a-84aa-4da3-8947-cd5a0541864c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>city_name</th>\n",
       "      <th>country</th>\n",
       "      <th>state</th>\n",
       "      <th>iso2</th>\n",
       "      <th>iso3</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>date</th>\n",
       "      <th>season</th>\n",
       "      <th>avg_temp_c</th>\n",
       "      <th>min_temp_c</th>\n",
       "      <th>max_temp_c</th>\n",
       "      <th>precipitation_mm</th>\n",
       "      <th>snow_depth_mm</th>\n",
       "      <th>avg_wind_dir_deg</th>\n",
       "      <th>avg_wind_speed_kmh</th>\n",
       "      <th>peak_wind_gust_kmh</th>\n",
       "      <th>avg_sea_level_pres_hpa</th>\n",
       "      <th>sunshine_total_min</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>1855-02-01</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-8.5</td>\n",
       "      <td>-4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>1855-02-02</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-12.1</td>\n",
       "      <td>-3.8</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>1855-02-03</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-17.5</td>\n",
       "      <td>-8.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>1855-02-04</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-11.4</td>\n",
       "      <td>-6.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>1855-02-05</td>\n",
       "      <td>Winter</td>\n",
       "      <td>NaN</td>\n",
       "      <td>-7.5</td>\n",
       "      <td>-1.3</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193114</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>2023-08-30</td>\n",
       "      <td>Summer</td>\n",
       "      <td>15.6</td>\n",
       "      <td>11.9</td>\n",
       "      <td>19.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>239.0</td>\n",
       "      <td>9.8</td>\n",
       "      <td>24.1</td>\n",
       "      <td>1010.8</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193115</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>2023-08-31</td>\n",
       "      <td>Summer</td>\n",
       "      <td>16.2</td>\n",
       "      <td>12.0</td>\n",
       "      <td>21.1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>203.0</td>\n",
       "      <td>10.4</td>\n",
       "      <td>25.9</td>\n",
       "      <td>1012.1</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193116</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>2023-09-01</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>16.7</td>\n",
       "      <td>12.2</td>\n",
       "      <td>21.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>190.0</td>\n",
       "      <td>11.0</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1015.5</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193117</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>2023-09-02</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>17.6</td>\n",
       "      <td>13.3</td>\n",
       "      <td>22.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>226.0</td>\n",
       "      <td>11.7</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1017.5</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193118</th>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>2023-09-03</td>\n",
       "      <td>Autumn</td>\n",
       "      <td>18.5</td>\n",
       "      <td>13.5</td>\n",
       "      <td>23.9</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>190.0</td>\n",
       "      <td>11.5</td>\n",
       "      <td>27.8</td>\n",
       "      <td>1017.6</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>193119 rows × 19 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       city_name  country   state iso2 iso3   latitude  longitude        date  \\\n",
       "0         Vienna  Austria    Wien   AT  AUT  48.200015  16.366639  1855-02-01   \n",
       "1         Vienna  Austria    Wien   AT  AUT  48.200015  16.366639  1855-02-02   \n",
       "2         Vienna  Austria    Wien   AT  AUT  48.200015  16.366639  1855-02-03   \n",
       "3         Vienna  Austria    Wien   AT  AUT  48.200015  16.366639  1855-02-04   \n",
       "4         Vienna  Austria    Wien   AT  AUT  48.200015  16.366639  1855-02-05   \n",
       "...          ...      ...     ...  ...  ...        ...        ...         ...   \n",
       "193114    Berlin  Germany  Berlin   DE  DEU  52.521819  13.401549  2023-08-30   \n",
       "193115    Berlin  Germany  Berlin   DE  DEU  52.521819  13.401549  2023-08-31   \n",
       "193116    Berlin  Germany  Berlin   DE  DEU  52.521819  13.401549  2023-09-01   \n",
       "193117    Berlin  Germany  Berlin   DE  DEU  52.521819  13.401549  2023-09-02   \n",
       "193118    Berlin  Germany  Berlin   DE  DEU  52.521819  13.401549  2023-09-03   \n",
       "\n",
       "        season  avg_temp_c  min_temp_c  max_temp_c  precipitation_mm  \\\n",
       "0       Winter         NaN        -8.5        -4.0               NaN   \n",
       "1       Winter         NaN       -12.1        -3.8               NaN   \n",
       "2       Winter         NaN       -17.5        -8.3               NaN   \n",
       "3       Winter         NaN       -11.4        -6.3               NaN   \n",
       "4       Winter         NaN        -7.5        -1.3               NaN   \n",
       "...        ...         ...         ...         ...               ...   \n",
       "193114  Summer        15.6        11.9        19.7               NaN   \n",
       "193115  Summer        16.2        12.0        21.1               NaN   \n",
       "193116  Autumn        16.7        12.2        21.7               NaN   \n",
       "193117  Autumn        17.6        13.3        22.5               NaN   \n",
       "193118  Autumn        18.5        13.5        23.9               NaN   \n",
       "\n",
       "        snow_depth_mm  avg_wind_dir_deg  avg_wind_speed_kmh  \\\n",
       "0                 NaN               NaN                 NaN   \n",
       "1                 NaN               NaN                 NaN   \n",
       "2                 NaN               NaN                 NaN   \n",
       "3                 NaN               NaN                 NaN   \n",
       "4                 NaN               NaN                 NaN   \n",
       "...               ...               ...                 ...   \n",
       "193114            NaN             239.0                 9.8   \n",
       "193115            NaN             203.0                10.4   \n",
       "193116            NaN             190.0                11.0   \n",
       "193117            NaN             226.0                11.7   \n",
       "193118            NaN             190.0                11.5   \n",
       "\n",
       "        peak_wind_gust_kmh  avg_sea_level_pres_hpa  sunshine_total_min  \n",
       "0                      NaN                     NaN                 NaN  \n",
       "1                      NaN                     NaN                 NaN  \n",
       "2                      NaN                     NaN                 NaN  \n",
       "3                      NaN                     NaN                 NaN  \n",
       "4                      NaN                     NaN                 NaN  \n",
       "...                    ...                     ...                 ...  \n",
       "193114                24.1                  1010.8                 NaN  \n",
       "193115                25.9                  1012.1                 NaN  \n",
       "193116                27.8                  1015.5                 NaN  \n",
       "193117                27.8                  1017.5                 NaN  \n",
       "193118                27.8                  1017.6                 NaN  \n",
       "\n",
       "[193119 rows x 19 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#si on tente de faire la jointure sur les noms des villes\n",
    "df_merge = pd.merge(df_cities, df_weather, how='right', on='city_name')\n",
    "df_merge\n",
    "df_merge.drop(['station_id_x', 'station_id_y'], axis=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9afd67c0-3508-4306-90c7-7ae8f534b61f",
   "metadata": {},
   "source": [
    "On voit que l'on a conservé le même nombre de lignes que sur **weather**, la jointure a bien été effectuée.\n",
    "\n",
    "Il suffisait de faire la jointure sur les noms des villes, et on n'avait pas de problème avec \"objet VS entier\"..."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a99f4702-f15f-43b1-bb66-94683ef90394",
   "metadata": {},
   "source": [
    "On peut maintenant effectuer la jointure totale des trois tables (ici de **merge** avec **countries** ; on va la faire encore sur la colonne du nom de ville puisque les 4 villes sont toutes des capitales, puis on éliminera les colonnes doublons. Avant de la créer, pour éviter de supprimer des doublons après-coup, on peut les supprimer en amont."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "042f3265-bd51-422c-877f-f063e0c73749",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>station_id_x</th>\n",
       "      <th>city_name</th>\n",
       "      <th>country_x</th>\n",
       "      <th>state</th>\n",
       "      <th>iso2_x</th>\n",
       "      <th>iso3_x</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>station_id_y</th>\n",
       "      <th>date</th>\n",
       "      <th>...</th>\n",
       "      <th>native_name</th>\n",
       "      <th>iso2_y</th>\n",
       "      <th>iso3_y</th>\n",
       "      <th>population</th>\n",
       "      <th>area</th>\n",
       "      <th>capital</th>\n",
       "      <th>capital_lat</th>\n",
       "      <th>capital_lng</th>\n",
       "      <th>region</th>\n",
       "      <th>continent</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>11035</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>11035</td>\n",
       "      <td>1855-02-01</td>\n",
       "      <td>...</td>\n",
       "      <td>Österreich</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>8527230.0</td>\n",
       "      <td>83871.0</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>48.208354</td>\n",
       "      <td>16.372504</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>11035</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>11035</td>\n",
       "      <td>1855-02-02</td>\n",
       "      <td>...</td>\n",
       "      <td>Österreich</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>8527230.0</td>\n",
       "      <td>83871.0</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>48.208354</td>\n",
       "      <td>16.372504</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>11035</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>11035</td>\n",
       "      <td>1855-02-03</td>\n",
       "      <td>...</td>\n",
       "      <td>Österreich</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>8527230.0</td>\n",
       "      <td>83871.0</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>48.208354</td>\n",
       "      <td>16.372504</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>11035</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>11035</td>\n",
       "      <td>1855-02-04</td>\n",
       "      <td>...</td>\n",
       "      <td>Österreich</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>8527230.0</td>\n",
       "      <td>83871.0</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>48.208354</td>\n",
       "      <td>16.372504</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>11035</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>Austria</td>\n",
       "      <td>Wien</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>48.200015</td>\n",
       "      <td>16.366639</td>\n",
       "      <td>11035</td>\n",
       "      <td>1855-02-05</td>\n",
       "      <td>...</td>\n",
       "      <td>Österreich</td>\n",
       "      <td>AT</td>\n",
       "      <td>AUT</td>\n",
       "      <td>8527230.0</td>\n",
       "      <td>83871.0</td>\n",
       "      <td>Vienna</td>\n",
       "      <td>48.208354</td>\n",
       "      <td>16.372504</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193114</th>\n",
       "      <td>10384</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>10384</td>\n",
       "      <td>2023-08-30</td>\n",
       "      <td>...</td>\n",
       "      <td>Deutschland</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>80783000.0</td>\n",
       "      <td>357114.0</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>52.517036</td>\n",
       "      <td>13.388860</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193115</th>\n",
       "      <td>10384</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>10384</td>\n",
       "      <td>2023-08-31</td>\n",
       "      <td>...</td>\n",
       "      <td>Deutschland</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>80783000.0</td>\n",
       "      <td>357114.0</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>52.517036</td>\n",
       "      <td>13.388860</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193116</th>\n",
       "      <td>10384</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>10384</td>\n",
       "      <td>2023-09-01</td>\n",
       "      <td>...</td>\n",
       "      <td>Deutschland</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>80783000.0</td>\n",
       "      <td>357114.0</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>52.517036</td>\n",
       "      <td>13.388860</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193117</th>\n",
       "      <td>10384</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>10384</td>\n",
       "      <td>2023-09-02</td>\n",
       "      <td>...</td>\n",
       "      <td>Deutschland</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>80783000.0</td>\n",
       "      <td>357114.0</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>52.517036</td>\n",
       "      <td>13.388860</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>193118</th>\n",
       "      <td>10384</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>Germany</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>52.521819</td>\n",
       "      <td>13.401549</td>\n",
       "      <td>10384</td>\n",
       "      <td>2023-09-03</td>\n",
       "      <td>...</td>\n",
       "      <td>Deutschland</td>\n",
       "      <td>DE</td>\n",
       "      <td>DEU</td>\n",
       "      <td>80783000.0</td>\n",
       "      <td>357114.0</td>\n",
       "      <td>Berlin</td>\n",
       "      <td>52.517036</td>\n",
       "      <td>13.388860</td>\n",
       "      <td>Western Europe</td>\n",
       "      <td>Europe</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>193119 rows × 32 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       station_id_x city_name country_x   state iso2_x iso3_x   latitude  \\\n",
       "0             11035    Vienna   Austria    Wien     AT    AUT  48.200015   \n",
       "1             11035    Vienna   Austria    Wien     AT    AUT  48.200015   \n",
       "2             11035    Vienna   Austria    Wien     AT    AUT  48.200015   \n",
       "3             11035    Vienna   Austria    Wien     AT    AUT  48.200015   \n",
       "4             11035    Vienna   Austria    Wien     AT    AUT  48.200015   \n",
       "...             ...       ...       ...     ...    ...    ...        ...   \n",
       "193114        10384    Berlin   Germany  Berlin     DE    DEU  52.521819   \n",
       "193115        10384    Berlin   Germany  Berlin     DE    DEU  52.521819   \n",
       "193116        10384    Berlin   Germany  Berlin     DE    DEU  52.521819   \n",
       "193117        10384    Berlin   Germany  Berlin     DE    DEU  52.521819   \n",
       "193118        10384    Berlin   Germany  Berlin     DE    DEU  52.521819   \n",
       "\n",
       "        longitude  station_id_y        date  ...  native_name  iso2_y  iso3_y  \\\n",
       "0       16.366639         11035  1855-02-01  ...   Österreich      AT     AUT   \n",
       "1       16.366639         11035  1855-02-02  ...   Österreich      AT     AUT   \n",
       "2       16.366639         11035  1855-02-03  ...   Österreich      AT     AUT   \n",
       "3       16.366639         11035  1855-02-04  ...   Österreich      AT     AUT   \n",
       "4       16.366639         11035  1855-02-05  ...   Österreich      AT     AUT   \n",
       "...           ...           ...         ...  ...          ...     ...     ...   \n",
       "193114  13.401549         10384  2023-08-30  ...  Deutschland      DE     DEU   \n",
       "193115  13.401549         10384  2023-08-31  ...  Deutschland      DE     DEU   \n",
       "193116  13.401549         10384  2023-09-01  ...  Deutschland      DE     DEU   \n",
       "193117  13.401549         10384  2023-09-02  ...  Deutschland      DE     DEU   \n",
       "193118  13.401549         10384  2023-09-03  ...  Deutschland      DE     DEU   \n",
       "\n",
       "        population      area  capital  capital_lat  capital_lng  \\\n",
       "0        8527230.0   83871.0   Vienna    48.208354    16.372504   \n",
       "1        8527230.0   83871.0   Vienna    48.208354    16.372504   \n",
       "2        8527230.0   83871.0   Vienna    48.208354    16.372504   \n",
       "3        8527230.0   83871.0   Vienna    48.208354    16.372504   \n",
       "4        8527230.0   83871.0   Vienna    48.208354    16.372504   \n",
       "...            ...       ...      ...          ...          ...   \n",
       "193114  80783000.0  357114.0   Berlin    52.517036    13.388860   \n",
       "193115  80783000.0  357114.0   Berlin    52.517036    13.388860   \n",
       "193116  80783000.0  357114.0   Berlin    52.517036    13.388860   \n",
       "193117  80783000.0  357114.0   Berlin    52.517036    13.388860   \n",
       "193118  80783000.0  357114.0   Berlin    52.517036    13.388860   \n",
       "\n",
       "                region  continent  \n",
       "0       Western Europe     Europe  \n",
       "1       Western Europe     Europe  \n",
       "2       Western Europe     Europe  \n",
       "3       Western Europe     Europe  \n",
       "4       Western Europe     Europe  \n",
       "...                ...        ...  \n",
       "193114  Western Europe     Europe  \n",
       "193115  Western Europe     Europe  \n",
       "193116  Western Europe     Europe  \n",
       "193117  Western Europe     Europe  \n",
       "193118  Western Europe     Europe  \n",
       "\n",
       "[193119 rows x 32 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_merge_triple = pd.merge(df_merge, df_countries, left_on='city_name', right_on='capital', how='left')\n",
    "df_merge_triple"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "728a1bc6-7d3a-4cef-a767-351b7dda8101",
   "metadata": {},
   "source": [
    "Je ne comprends pas pourquoi les station_id réapparaissent..."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4bc55664-acd8-4a09-ab0f-9cf02cfb68a3",
   "metadata": {},
   "source": [
    "Bon, on va arrêter le massacre ici :("
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
